"""Deterministic execution of a validated QuerySpec.

Nothing in this module interprets natural language and nothing accepts code from
the model. Operators map to a fixed dispatch table of functions; there is no
`eval`, no `df.query()` with interpolated strings, and no dynamic attribute
access. The same spec always produces the same result.

Every number a user sees is computed here, by pandas -- never generated by the
LLM. That is the whole point of the split.
"""

from __future__ import annotations

import math

import numpy as np
import pandas as pd

from app.data_store import DataStore, normalize_spec
from app.models import (
    COLUMN_LABELS,
    COLUMN_PLURALS,
    COLUMNS,
    DATE_COLUMN,
    DEFAULT_LIST_LIMIT,
    MAX_LIST_LIMIT,
    NULLABLE_COLUMNS,
    STRING_COLUMNS,
    AppliedDateRange,
    Filter,
    GroupResult,
    Intent,
    Metric,
    Op,
    QueryResult,
    QuerySpec,
    UnsupportedQueryError,
)
from app.query import dates

# --------------------------------------------------------------------------
# Operator dispatch
# --------------------------------------------------------------------------


def _mask(series: pd.Series) -> np.ndarray:
    """Normalise a comparison result to a plain boolean mask.

    Comparisons against NA propagate NA in pandas. For filtering, an unknown
    value never satisfies a predicate, so NA becomes False.
    """
    return series.fillna(False).to_numpy(dtype=bool)


def _norm(series: pd.Series) -> pd.Series:
    """Case-insensitive view of a text column."""
    return series.astype("string").str.lower()


def _to_day(value) -> pd.Timestamp:
    """Parse a 'YYYY-MM-DD' string to a normalised Timestamp."""
    try:
        ts = pd.Timestamp(value)
    except (ValueError, TypeError) as exc:
        raise UnsupportedQueryError(
            f"'{value}' is not a valid date; expected YYYY-MM-DD"
        ) from exc
    if pd.isna(ts):
        raise UnsupportedQueryError(f"'{value}' is not a valid date; expected YYYY-MM-DD")
    return ts.normalize()


def _apply_date_filter(col: pd.Series, op: Op, val) -> np.ndarray:
    """Equality/membership on a timestamp column means 'on that calendar day'.

    Comparing a datetime column to a date string directly matches nothing,
    because no ticket lands exactly at midnight. Silently returning zero rows is
    worse than being wrong loudly, so the comparison is done on the date part.
    Ranges are deliberately not handled here -- those go through date_range.
    """
    day = col.dt.normalize()

    if op is Op.EQ:
        return _mask(day == _to_day(val))
    if op is Op.NE:
        return _mask(day != _to_day(val)) & _mask(col.notna())
    if op is Op.IN:
        wanted = [_to_day(v) for v in val]
        return _mask(day.isin(wanted))
    if op is Op.NOT_IN:
        wanted = [_to_day(v) for v in val]
        return _mask(~day.isin(wanted)) & _mask(col.notna())

    raise UnsupportedQueryError(
        f"operator '{op.value}' is not supported on {DATE_COLUMN}; use date_range"
    )


def _apply_filter(df: pd.DataFrame, f: Filter) -> np.ndarray:
    col = df[f.field]
    op, val = f.op, f.value

    if op is Op.IS_NULL:
        return _mask(col.isna())
    if op is Op.NOT_NULL:
        return _mask(col.notna())

    if f.field == DATE_COLUMN:
        return _apply_date_filter(col, op, val)

    text = f.field in STRING_COLUMNS

    if op is Op.EQ:
        return _mask(_norm(col) == val.lower()) if text else _mask(col == val)
    if op is Op.NE:
        # NE must not match rows where the value is unknown.
        base = _norm(col) != val.lower() if text else col != val
        return _mask(base) & _mask(col.notna())
    if op is Op.IN:
        if text:
            wanted = {str(v).lower() for v in val}
            return _mask(_norm(col).isin(wanted))
        return _mask(col.isin(list(val)))
    if op is Op.NOT_IN:
        if text:
            wanted = {str(v).lower() for v in val}
            base = ~_norm(col).isin(wanted)
        else:
            base = ~col.isin(list(val))
        return _mask(base) & _mask(col.notna())
    if op is Op.CONTAINS:
        return _mask(_norm(col).str.contains(str(val).lower(), regex=False, na=False))
    if op is Op.GT:
        return _mask(col > val)
    if op is Op.GTE:
        return _mask(col >= val)
    if op is Op.LT:
        return _mask(col < val)
    if op is Op.LTE:
        return _mask(col <= val)

    raise UnsupportedQueryError(f"unhandled operator '{op}'")


def _describe_filter(f: Filter) -> str:
    label = COLUMN_LABELS.get(f.field, f.field)
    words = {
        Op.EQ: "is", Op.NE: "is not", Op.GT: ">", Op.GTE: ">=",
        Op.LT: "<", Op.LTE: "<=", Op.IN: "in", Op.NOT_IN: "not in",
        Op.CONTAINS: "contains", Op.IS_NULL: "is missing", Op.NOT_NULL: "is present",
    }
    if f.op in (Op.IS_NULL, Op.NOT_NULL):
        return f"{label} {words[f.op]}"
    if isinstance(f.value, (list, tuple)):
        return f"{label} {words[f.op]} ({', '.join(str(v) for v in f.value)})"
    return f"{label} {words[f.op]} {f.value}"


# --------------------------------------------------------------------------
# Filtering
# --------------------------------------------------------------------------


def _filter_rows(
    df: pd.DataFrame, spec: QuerySpec, anchor: pd.Timestamp
) -> tuple[pd.DataFrame, AppliedDateRange]:
    mask = np.ones(len(df), dtype=bool)

    start, end = dates.resolve(spec.date_range, anchor)
    if start is not None:
        mask &= _mask(df[DATE_COLUMN] >= start)
    if end is not None:
        mask &= _mask(df[DATE_COLUMN] < end)

    applied = AppliedDateRange(
        label=dates.describe(spec.date_range, (start, end)),
        start=start.date().isoformat() if start is not None else None,
        end=(end - pd.Timedelta(days=1)).date().isoformat() if end is not None else None,
    )

    for f in spec.filters:
        mask &= _apply_filter(df, f)

    # Each group is OR-internal; groups are ANDed with everything else.
    for group in spec.or_groups:
        group_mask = np.zeros(len(df), dtype=bool)
        for f in group:
            group_mask |= _apply_filter(df, f)
        mask &= group_mask

    return df[mask], applied


def filter_rows(
    df: pd.DataFrame, spec: QuerySpec, anchor: pd.Timestamp
) -> tuple[pd.DataFrame, AppliedDateRange]:
    """Public entry point for spec filtering.

    The anomaly detector calls this so filter semantics are defined in one
    place. Any change to how `eq`, `contains` or `or_groups` behave applies
    identically to queries and to anomaly population selection.
    """
    return _filter_rows(df, spec, anchor)


def describe_conditions(spec: QuerySpec, applied: AppliedDateRange) -> str:
    """Human-readable rendering of the conditions a spec applied."""
    return _conditions(spec, applied)


# --------------------------------------------------------------------------
# Aggregation
# --------------------------------------------------------------------------

_AGG = {
    Metric.AVG: lambda s: s.mean(),
    Metric.SUM: lambda s: s.sum(),
    Metric.MIN: lambda s: s.min(),
    Metric.MAX: lambda s: s.max(),
    Metric.MEDIAN: lambda s: s.median(),
}


def _scalar(value) -> float | int | None:
    if value is None:
        return None
    if isinstance(value, (np.integer,)):
        return int(value)
    if isinstance(value, (np.floating, float)):
        f = float(value)
        return None if math.isnan(f) else round(f, 2)
    if isinstance(value, (int,)):
        return int(value)
    return None


def _aggregate(frame: pd.DataFrame, spec: QuerySpec) -> tuple[float | int | None, int, int]:
    """Returns (value, n_used, n_total). n_used excludes nulls in the target."""
    n_total = len(frame)
    if spec.metric is Metric.COUNT:
        return n_total, n_total, n_total

    series = frame[spec.target]
    used = series.dropna()
    if used.empty:
        return None, 0, n_total
    return _scalar(_AGG[spec.metric](used)), int(len(used)), n_total


def _aggregate_grouped(frame: pd.DataFrame, spec: QuerySpec) -> list[GroupResult]:
    results: list[GroupResult] = []
    if frame.empty:
        return results

    for key, sub in frame.groupby(spec.group_by, observed=True, sort=True):
        value, n_used, n_total = _aggregate(sub, spec)
        results.append(
            GroupResult(group=str(key), value=value, n_used=n_used, n_total=n_total)
        )

    # Default ordering: largest value first. Ties are broken by group name so
    # the output is stable across runs.
    reverse = (spec.sort.direction if spec.sort else "desc") == "desc"
    sort_field = spec.sort.field if spec.sort else "value"

    if sort_field == "value":
        results.sort(key=lambda g: g.group)  # stable tie-break
        results.sort(
            key=lambda g: (g.value is None, g.value if g.value is not None else 0),
            reverse=reverse,
        )
    else:  # sorting by the group key itself
        results.sort(key=lambda g: g.group, reverse=reverse)

    return results


# --------------------------------------------------------------------------
# Answer formatting (deterministic -- no LLM involved)
# --------------------------------------------------------------------------


METRIC_WORDS = {
    Metric.AVG: "average",
    Metric.SUM: "total",
    Metric.MIN: "minimum",
    Metric.MAX: "maximum",
    Metric.MEDIAN: "median",
    Metric.COUNT: "count",
}


def _fmt(value: float | int | None) -> str:
    if value is None:
        return "n/a"
    if isinstance(value, int) or float(value).is_integer():
        return f"{int(value):,}"
    return f"{value:,.2f}"


def _conditions(spec: QuerySpec, applied: AppliedDateRange) -> str:
    parts = [_describe_filter(f) for f in spec.filters]
    for group in spec.or_groups:
        parts.append("(" + " or ".join(_describe_filter(f) for f in group) + ")")
    if applied.label != "all time":
        parts.append(f"created in {applied.label}")
    return " and ".join(parts)


def _build_answer(spec: QuerySpec, result: QueryResult, applied: AppliedDateRange) -> str:
    where = _conditions(spec, applied)
    suffix = f" where {where}" if where else ""

    if spec.intent is Intent.LIST:
        if result.matched_count == 0:
            return f"No tickets found{suffix}."
        shown = (
            f" Showing the first {result.returned_count}."
            if result.returned_count < result.matched_count
            else ""
        )
        noun = "ticket" if result.matched_count == 1 else "tickets"
        return f"Found {result.matched_count:,} {noun}{suffix}.{shown}"

    label = COLUMN_LABELS.get(spec.target, spec.target or "")

    if result.groups is not None:
        if not result.groups:
            return f"No tickets found{suffix}, so there is nothing to group."
        top = result.groups[0]
        group_label = COLUMN_LABELS.get(spec.group_by, spec.group_by)
        by_key = spec.sort is not None and spec.sort.field != "value"
        descending = spec.sort is None or spec.sort.direction == "desc"

        if by_key:
            # Ordered by group name, so "highest" would be a false claim.
            lead = f"{top.group} is first by {group_label}"
            if spec.metric is Metric.COUNT:
                lead += f" ({_fmt(top.value)} tickets)"
            else:
                lead += f" ({METRIC_WORDS[spec.metric]} {label} {_fmt(top.value)})"
        elif spec.metric is Metric.COUNT:
            rank = "highest" if descending else "lowest"
            lead = f"{top.group} has the {rank} ticket count ({_fmt(top.value)})"
        else:
            rank = "highest" if descending else "lowest"
            lead = (
                f"{top.group} has the {rank} {METRIC_WORDS[spec.metric]} {label} "
                f"({_fmt(top.value)})"
            )

        total = result.group_count
        if total <= 1:
            return f"{lead}{suffix}."

        plural = COLUMN_PLURALS.get(spec.group_by, f"{group_label}s")
        if len(result.groups) == total:
            shown = f" across {total} {plural}"
        elif len(result.groups) == 1:
            shown = f" out of {total} {plural}"
        else:
            shown = f", showing the top {len(result.groups)} of {total} {plural}"
        return f"{lead}{shown}{suffix}."

    if spec.metric is Metric.COUNT:
        noun = "ticket" if result.value == 1 else "tickets"
        return f"{_fmt(result.value)} {noun}{suffix}."

    if result.value is None:
        return (
            f"No {label} values available{suffix} "
            f"({result.n_total:,} ticket(s) matched but none had a {label})."
        )
    return f"The {METRIC_WORDS[spec.metric]} {label}{suffix} is {_fmt(result.value)}."


# --------------------------------------------------------------------------
# Entry point
# --------------------------------------------------------------------------


def execute(spec: QuerySpec, store: DataStore) -> QueryResult:
    """Run a validated spec against the store and return a structured result."""
    if spec.intent is Intent.UNSUPPORTED:
        raise UnsupportedQueryError(spec.reason or "query is not supported")
    if spec.intent is Intent.ANOMALY:
        raise UnsupportedQueryError(
            "anomaly queries are handled by the anomaly detector, not the executor"
        )

    # Canonicalise categorical values before anything touches the data. An
    # unresolvable value raises here rather than quietly matching nothing.
    spec = normalize_spec(spec, store)

    frame, applied = _filter_rows(store.df, spec, store.anchor)

    result = QueryResult(
        intent=spec.intent,
        metric=spec.metric,
        target=spec.target,
        matched_count=len(frame),
        date_range=applied,
    )

    if spec.intent is Intent.AGGREGATE:
        if spec.group_by:
            groups = _aggregate_grouped(frame, spec)
            result.group_count = len(groups)
            result.n_total = len(frame)
            # Counted over every group, before `limit` trims the display. The
            # aggregate really was computed across all of them, so summing only
            # the returned page would understate the denominator in the warning.
            result.n_used = sum(g.n_used for g in groups)
            if spec.limit:
                groups = groups[: spec.limit]
            result.groups = groups
            result.returned_count = len(groups)
        else:
            value, n_used, n_total = _aggregate(frame, spec)
            result.value = value
            result.n_used = n_used
            result.n_total = n_total
            result.returned_count = 1
    else:  # LIST
        if spec.sort and spec.sort.field != "value":
            frame = frame.sort_values(
                spec.sort.field,
                ascending=spec.sort.direction == "asc",
                na_position="last",
                kind="stable",
            )
        else:
            frame = frame.sort_values(DATE_COLUMN, ascending=False, kind="stable")

        limit = min(spec.limit or DEFAULT_LIST_LIMIT, MAX_LIST_LIMIT)
        if spec.limit and spec.limit > MAX_LIST_LIMIT:
            result.warnings.append(
                f"requested {spec.limit} rows; capped at {MAX_LIST_LIMIT}"
            )
        page = frame.head(limit)

        out = page.copy()
        out[DATE_COLUMN] = out[DATE_COLUMN].dt.strftime("%Y-%m-%d %H:%M")
        rows = out.astype(object).where(pd.notna(out), None).to_dict(orient="records")

        result.rows = rows
        result.columns = list(COLUMNS)
        result.returned_count = len(rows)
        result.n_total = len(frame)
        result.n_used = len(rows)

    # Honest denominators: an average over a nullable column silently drops the
    # tickets that have no value, so say so.
    if (
        spec.intent is Intent.AGGREGATE
        and spec.metric is not Metric.COUNT
        and spec.target in NULLABLE_COLUMNS
        and result.n_used < result.n_total
    ):
        label = COLUMN_LABELS.get(spec.target, spec.target)
        result.warnings.append(
            f"Computed over {result.n_used:,} of {result.n_total:,} matching tickets; "
            f"{result.n_total - result.n_used:,} have no {label} (unresolved)."
        )

    if result.matched_count == 0:
        result.warnings.append("No tickets matched the filters.")

    result.answer = _build_answer(spec, result, applied)
    return result
